name: DiagWiki
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
  - conda-forge
dependencies:
  - annotated-doc=0.0.4
  - annotated-types=0.6.0
  - anyio=4.10.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - click=8.2.1
  - expat=2.7.3
  - fastapi=0.121.1
  - h11=0.16.0
  - idna=3.11
  - libcxx=20.1.8
  - libexpat=2.7.3
  - libffi=3.4.4
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.6.0
  - pip=25.3
  - pydantic=2.12.4
  - pydantic-core=2.41.5
  - python=3.12.12
  - python-dotenv=1.2.1
  - readline=8.3
  - setuptools=80.9.0
  - sniffio=1.3.1
  - sqlite=3.51.0
  - starlette=0.47.3
  - tk=8.6.15
  - typing-extensions=4.15.0
  - typing-inspection=0.4.2
  - typing_extensions=4.15.0
  - tzdata=2025b
  - uvicorn=0.35.0
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.3.1
prefix: /Users/zhuyuezx/miniconda3/envs/DiagWiki
